## tensor flow is multidimensional arry
- 3d is  batch siz,rows ans cols

In [3]:
import tensorflow as tf
tensor_zero=tf.constant(4)
tensor_zero


<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [5]:
import numpy as np
ary=np.array([2,3,4])
print(ary)
convert_tensor=tf.convert_to_tensor(ary)
print(convert_tensor)

[2 3 4]
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [12]:
num_rows=2

In [ ]:
import tensorflow as tf

# Create a 2x2 matrix
matrix = tf.constant([[4.0, 7.0], [2.0, 6.0]])

# Compute the inverse
inverse_matrix = tf.linalg.inv(matrix)

print("Original matrix:")
print(matrix.numpy())

print("Inverse matrix:")
print(inverse_matrix.numpy())


In [19]:
import tensorflow as tf

# Define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.einsum('ij,jk->ik', A, B)

print("Matrix multiplication result:")
print(result.numpy())


Matrix multiplication result:
[[19 22]
 [43 50]]


In [20]:
import numpy as np

# Example: Batch of grayscale images
images = np.random.random((32, 128, 512))  # 32 images, each 128x512 pixels

print(images.shape)  # Output: (32, 128, 512)


(32, 128, 512)


In [3]:
import tensorflow as tf

# Create a 1D tensor
tensor = tf.ragged.constant([[1, 2, 3],[2,3,4],[3]])

print(tensor.shape)


(3, None)
